### ISSUE TITLE
Languages and Scripts

### ISSUE THREAD

**Issue by manufrancis** [TST-Project/mss#56]
Can you add the following languages and scripts?

Languages
* Hindi
* Marathi
* Malayalam

Scripts
* Marathi
* Malayalam

**Comment by chchch** [comment]
Should we use 'Modi' instead of 'Marathi' for the script? To follow Unicode/Wikipedia: https://en.wikipedia.org/wiki/Modi_script

There's also a bigger debate about what constitutes a unique and distinct "script", especially with varieties of Nāgarī... we currently don't distinguish between northern ('Kalkatīya') and southern ('Bambaīya') Nāgarī.

Of course, you also often find features from multiple "scripts" in the same manuscript... but anyway, that's a long discussion that gets pretty boring and can drag on until the end of time. I think it makes sense to note script "features" instead of making up new script names, since, one day, when we have enough data, we can then actually do some quantitative analyses based on material evidence, instead of just arguing.

**Comment by manufrancis** [comment]
My request was motivated by the following item:
https://tst-project.github.io/mss/Indien_0563b.xml
See picture from Didomena.
So let us go for Modi (script) and marathi (language).

**Comment by chchch** [comment]
Done!
